# Generated by Django 5.2.1 on 2025-06-04 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select a parent category to make this a subcategory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category'),
        ),
    ]
