# Generated by Django 5.2.2 on 2025-06-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='additional_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price difference for this variation, if any.', max_digits=10),
        ),
    ]
