# Generated by Django 5.2.2 on 2025-06-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_userprofile_address_line_1_userprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
    ]
