# Generated by Django 5.2.1 on 2025-06-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileSliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mobile_slider_images/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('link_url', models.URLField(blank=True, help_text='Optional: URL the slide links to.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the slide appears.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active slides will be displayed.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mobile Slider Image',
                'verbose_name_plural': 'Mobile Slider Images',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
