# Generated by Django 5.2.1 on 2025-06-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_alter_product_options_product_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoCarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the brand/logo (for internal reference or alt text)', max_length=100)),
                ('logo_image', models.ImageField(upload_to='logo_carousel/')),
                ('link_url', models.URLField(blank=True, help_text='Optional: URL the logo links to.', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the logo appears.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active logos will be displayed.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Logo Carousel Item',
                'verbose_name_plural': 'Logo Carousel Items',
                'ordering': ['order', 'name'],
            },
        ),
    ]
