# Generated by Django 5.2.1 on 2025-06-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_logocarouselitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the city', max_length=100, unique=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, help_text='Delivery fee for this city', max_digits=6)),
                ('is_active', models.BooleanField(default=True, help_text='Whether delivery is currently available to this city')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery City',
                'verbose_name_plural': 'Delivery Cities',
                'ordering': ['name'],
            },
        ),
    ]
