# Generated by Django 5.2.1 on 2025-06-03 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='e.g., Red, Blue, Green', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Image specific to this color variation.', null=True, upload_to='products/variations/')),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'ordering': ['product', 'color_name'],
                'unique_together': {('product', 'color_name')},
            },
        ),
    ]
