# Generated by Django 5.2.1 on 2025-06-03 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_product_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Additional image for the product gallery.', upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, help_text='Descriptive text for the image.', max_length=255, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the image in the gallery.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['product', 'order'],
            },
        ),
    ]
