# Generated by Django 5.2.2 on 2025-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image for the category.', null=True, upload_to='categories/'),
        ),
    ]
