# Generated by Django 5.2.2 on 2025-06-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['product', 'color_name', 'size', 'brand'], 'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand of the product variation.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='rating',
            field=models.IntegerField(choices=[(0, 'No Rating'), (1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0, help_text='Rating of the product variation.'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='size',
            field=models.CharField(blank=True, choices=[('', 'No Size'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large')], default='', help_text='Size of the product variation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='image',
            field=models.ImageField(blank=True, help_text='Image specific to this variation.', null=True, upload_to='products/variations/'),
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'color_name', 'size', 'brand')},
        ),
    ]
