# Generated by Django 5.2.2 on 2025-06-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_add_old_price_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
