# Generated by Django 5.2.2 on 2025-06-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_add_old_price_field_again'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand of the product.', max_length=100, null=True),
        ),
    ]
