# Generated by Django 5.2.2 on 2025-06-09 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_add_brand_to_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariation',
            options={'ordering': ['product', 'color_name', 'size'], 'verbose_name': 'Product Variation', 'verbose_name_plural': 'Product Variations'},
        ),
        migrations.AlterUniqueTogether(
            name='productvariation',
            unique_together={('product', 'color_name', 'size')},
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='brand',
        ),
    ]
